export const UI_TEXT = {
  "zh-CN": {
    productTitle: "MacBook 设置建议",
    tagline: "理解变化，手动调整，需要时恢复原状",
    search: "搜索 MacBook 设置建议",
    noResults: "没有找到相关设置",
    clearSearch: "清除搜索",
    retry: "重新加载",
    loadError: "设置读取失败。请通过项目提供的本地服务器或在线网页打开，而不是直接双击 index.html。",
    introTitle: "从左侧选择一项设置",
    introDescription: "这份指南聚焦访达、系统设置与工具和快捷操作。每项都说明可见变化、修改路径和恢复方法。",
    introWorkflow: "根据自己的工作习惯决定是否采用，不把建议当作统一答案。",
    introCheck: "左栏方框仅仅是为了方便检查是否修改，没有一键修改的作用。",
    introStorage: "进度只保存在当前浏览器，不会同步到其他设备。",
    introScope: "画面是概念示意；设置名称与位置可能随 macOS 更新而变化。",
    before: "修改前",
    after: "修改后",
    concept: "概念示意",
    replay: "重新播放",
    play: "播放演示",
    fileLoaded: "文件已加入",
    hotDesktopFlow: "移到右下角 → 拖住桌面文件 → 再移到右下角 → 放入 App",
    prerequisites: "开始前",
    conflicts: "注意",
    path: "修改路径",
    steps: "如何修改",
    restore: "如何恢复？",
    sources: "来源",
    ungrouped: "未分组",
    checkbox: (title) => `标记“${title}”已处理`,
    saveError: "进度暂时无法保存；本次选择可能在刷新后丢失。",
    unsupportedVisual: "暂无视觉示意",
    projectMaterials: "设置资料",
    folders: ["01 截图", "02 备份", "03 笔记"],
    pathVisible: "Macintosh HD  ›  用户  ›  文稿  ›  Mac Setup",
    pathHidden: "路径栏隐藏",
    exampleFilesBefore: ["设置笔记", "使用指南", "操作演示"],
    exampleFilesAfter: ["设置笔记.txt", "使用指南.pdf", "操作演示.mov"],
    chineseDocument: "中文设置笔记",
    englishDocument: "English Setup Notes",
    pinyin: "拼音",
    lightTap: "仅需轻触",
    pressRequired: "需要压力",
    selected: "已选择",
    setupFolder: "设置资料",
    tapToDrop: "轻点放下",
    sameDistance: "相同手指距离",
    slow: "慢",
    lower: "较低",
    suggestedSpeed: "倒数第三格",
    fast: "快",
    dockBefore: "前三个为固定 App；分隔线后为建议或最近使用的 App",
    dockAfter: "固定 App 不变；此段不再显示建议与最近 App",
    window: "窗口",
    hotDesktopTitle: "右下角：显示桌面并带文件返回",
    desktop: "桌面",
    currentApp: "当前 App",
    dropHere: "将文件放在这里",
    bottomRight: "右下角",
    hotSleepTitle: "Command + 右上角：使显示器进入睡眠",
    holdCommand: "按住 Command",
    display: "显示器",
    topRight: "右上角",
    sleeping: "进入睡眠",
    settingsApp: "系统设置",
  },
  en: {
    productTitle: "MacBook Setup Recommendations",
    tagline: "Understand the change, adjust it manually, and restore it when needed",
    search: "Search MacBook setup recommendations",
    noResults: "No matching settings",
    clearSearch: "Clear search",
    retry: "Reload",
    loadError: "Settings could not be loaded. Open this project through its local server or a hosted site instead of double-clicking index.html.",
    introTitle: "Choose a setting from the sidebar",
    introDescription: "This guide covers Finder, System Settings, and utilities and shortcuts. Each item explains the visible change, where to find it, and how to restore it.",
    introWorkflow: "Decide whether each recommendation fits your workflow; these are not universal defaults.",
    introCheck: "The sidebar checkbox only helps you check whether you changed a setting; it cannot change the setting for you.",
    introStorage: "Progress stays in this browser and is not synced to other devices.",
    introScope: "Visuals are conceptual. Setting names and locations may change with macOS updates.",
    before: "Before",
    after: "After",
    concept: "Concept visual",
    replay: "Replay",
    play: "Play demo",
    fileLoaded: "File added",
    hotDesktopFlow: "Move to bottom-right → Drag a desktop file → Return via bottom-right → Drop into the app",
    prerequisites: "Before you start",
    conflicts: "Note",
    path: "Where to find it",
    steps: "How to change it",
    restore: "How to restore it",
    sources: "Sources",
    ungrouped: "Ungrouped",
    checkbox: (title) => `Mark “${title}” as handled`,
    saveError: "Progress could not be saved. This selection may be lost after a refresh.",
    unsupportedVisual: "No visual available",
    projectMaterials: "Setup Files",
    folders: ["01 Screenshots", "02 Backups", "03 Notes"],
    pathVisible: "Macintosh HD  ›  Users  ›  Documents  ›  Mac Setup",
    pathHidden: "Path bar hidden",
    exampleFilesBefore: ["Setup Notes", "Setup Guide", "Setup Demo"],
    exampleFilesAfter: ["Setup Notes.txt", "Setup Guide.pdf", "Setup Demo.mov"],
    chineseDocument: "Chinese Setup Notes",
    englishDocument: "English Setup Notes",
    pinyin: "Pinyin",
    lightTap: "A light tap",
    pressRequired: "Press down",
    selected: "Selected",
    setupFolder: "Setup Files",
    tapToDrop: "Tap to drop",
    sameDistance: "Same finger movement",
    slow: "Slow",
    lower: "Lower",
    suggestedSpeed: "Third from right",
    fast: "Fast",
    dockBefore: "The first three apps are pinned; suggested or recent apps appear after the divider",
    dockAfter: "Pinned apps stay; the suggested/recent section is hidden",
    window: "Window",
    hotDesktopTitle: "Bottom-right: show the desktop and bring a file back",
    desktop: "Desktop",
    currentApp: "Current App",
    dropHere: "Drop a file here",
    bottomRight: "Bottom-right",
    hotSleepTitle: "Command + top-right: put the display to sleep",
    holdCommand: "Hold Command",
    display: "Display",
    topRight: "Top-right",
    sleeping: "Sleeping",
    settingsApp: "System Settings",
  },
};
